
name: Reclutamiento de Agentes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  reporte-de-reclutamiento:
    runs-on: ubuntu-latest

    steps:
      - name: El Agente se presenta
        run: |
          echo "Hola, soy el Agente de Reclutamiento"
          echo "Estoy listo para recibir el reporte de reclutamiento 🤖"